### ISSUE TITLE
Unable to instantiate Program

### ISSUE THREAD

**Issue by eyevz** [kevinheavey/anchorpy#31]
Using the Jet Protocol IDL, copied here: https://gist.github.com/eyevz/fe7e9265b42c8fc7e4ff622498f6608a, I get the following error when trying to instantiate a program like `Program(idl, jd.JET_V1_KEY, Provider.local())`.

`ValueError: Unrecognized variant type: <class 'anchorpy.borsh_extension._DataclassStruct'>`

I can successfully instantiate and inspect the IDL itself using `idl = Idl.from_json(raw_idl)`.

**Comment by eyevz** [comment]
I changed this line:

https://github.com/kevinheavey/anchorpy/blob/ea302fe0c85c8315dc7d2be9c69fc786a8759484/src/anchorpy/coder/idl.py#L109

to

```pythjon
renamed = variant_name / _DataclassStruct(cstruct, datacls=datacls).subcon
```

and then I can instantiate `Program`. I have no idea what I'm doing though, so please say whether this is reasonable.

**Comment by kevinheavey** [comment]
Thanks for digging in and making this easy to replicate! It turns out none of the tests covered C-like struct variants of an enum, and those would all run into this error that you encountered. Pushing a fix now, it's pretty similar to what you're doing (we don't want to use `_DataclassStruct` here at all)
