### ISSUE TITLE
Baked-in PROGRAM_ID lacking flexibility

### ISSUE THREAD

**Issue by losman0s** [kevinheavey/anchorpy#80]
I might be missing something, but the baked-in a static `PROGRAM_ID` in ix builder helpers and `Account` struct fetch methods seems to reduce the flexibility of the generated client. To be able to point this client to a program deployed on different clusters with potentially different addresses, I find myself having to comment out the `program_id` check in account fetch methods, and wrap ix builders in something like:

```python
def make_deposit_ix(accounts: DepositAccounts, program_id: PublicKey):
    ix = generated.deposit(generated.DepositAccounts(...))
    ix = TransactionInstruction(ix.keys, program_id, ix.data)
    return ix
```

Instead, a possibility is for the fetch method to either:
- take in a `Program` object instead of a straight `AsyncClient`, and use the `program_id` it packs
- take an optional `program_id` argument defaulting to the static `PROGRAM_ID`

and ix builders could use the optional `program_id` arg as well.

Let me know what you think. I can create a PR for these changes if interested.

**Comment by kevinheavey** [comment]
Thanks for raising, this is something that needs fixing for sure. I like the optional program_id argument.

Interesting to note: the typescript anchor-client-gen uses neither solution, it just lets you write logic in the programId.ts file to decide what the program ID is. However this is only run once at import time, which means you can't change the program ID after importing it.

So for this reason I prefer adding an optional program_id param to places that need it. I don't like using the Program object because then we're back to needing the IDL file at runtime which makes things a bit messier.
